subsys/bluetooth/host/Kconfig

Add Kconfig file for bluetooth subsystem configuration.
Signed-off-by: Juan Vazquez <juan.vazquez@alifsemi.com>
(cherry picked from commit 85769db92e96bc2450851470fd751f53c4ec4eaa)

subsys: bluetooth: add BLE host Kconfig

---

samples/drivers/video/README.rst
samples/drivers/video/boards/alif_b1_dk_rtss_he.overlay
samples/drivers/video/boards/alif_e1c_dk_rtss_he.overlay

- Added README.rst file for video sample.
- Fixed warning of unnecessary address-cells/size-cells usage for child node endpoint of lpcam node in overlay files for E1C and B1 board.

samples: drivers: video: warning fix for lpcam node

---

samples/drivers/video/boards/alif_e7_dk_rtss_he.overlay
samples/drivers/video/boards/alif_e7_dk_rtss_hp.overlay

- Configured mt9m114 and arx3a0 camera sensors using overlay files for ensemble e7 board since video sample uses them.

samples: drivers: video: overlays to configure camera sensors in video sample

---

west.yml

This update takes compliance fixes from zephyr_alif into use

Updated Zephyr_alif hash to latest commit.

---

samples/bluetooth/le_audio/broadcast_sink/boards/alif_b1_fpga_rtss_he_ble.conf
samples/bluetooth/le_audio/broadcast_source/boards/alif_b1_fpga_rtss_he_ble.conf
samples/bluetooth/le_periph_hr/src/main.c
west.yml

FPGA uses version 1.2 of the BLE&802154&LC3 ROM code.
Depends on alifsemi/zephyr_alif#46.

manifest: update zephyr_alif

---

west.yml

es0 sleep configuration support.
Depends on alifsemi/zephyr_alif#51.

manifest: Zephyr_alif update

---

samples/drivers/spi_flash/src/main.c
west.yml

Added Test case for XiP Mode read from OSPI1 memory space.
Depends on alifsemi/zephyr_alif#54.

samples: flash: XiP Mode Test Case

---

boards/arm/alif_b1_devkit/alif_b1_dk_rtss_he_UART0_RTS_CTS.overlay
boards/arm/alif_e1c_devkit/alif_e1c_dk_rtss_he_UART0_RTS_CTS.overlay
boards/arm/alif_e3_devkit/alif_e3_dk_rtss_he_hp_UART0_RTS_CTS.overlay
boards/arm/alif_e7_devkit/alif_e7_dk_rtss_he_hp_UART0_RTS_CTS.overlay

Add an overlay to enable UART auto flow control for Balletto and Ensemble boards.

boards: arm: balletto/ensemble: Add overlay for UART auto flow control

---

west.yml

Added baud2 delay support for max OSPI bus clock on E1C/B1.

manifest: Zephyr manifest update

---

samples/drivers/spi_dw/boards/alif_e3_dk_rtss_he.overlay
samples/drivers/spi_dw/boards/alif_e7_dk_rtss_he.overlay
samples/drivers/spi_dw/src/main.c

- Added support for multiple simultaneous DMA instances in SPI sample overlays for Ensemble E3 and E7.
- Updated DMA configuration for both master and slave SPI in the sample application.
Depends on alifsemi/zephyr_alif#20.

samples: spi: Add support for simultaneously operating DMA instances

---

west.yml

BLE UTIMER dependency fix.
Zephyr PR https://github.com/alifsemi/zephyr_alif/pull/98

manifest: Zephyr updated

---

samples/drivers/spi_flash/boards/alif_b1_dk_rtss_he.overlay
samples/drivers/spi_flash/boards/alif_e1c_dk_rtss_he.overlay
samples/drivers/spi_flash/boards/alif_e7_dk_rtss_he.overlay
samples/drivers/spi_flash/boards/alif_e7_dk_rtss_hp.overlay
samples/drivers/spi_flash/src/main.c

Supporting 8-bit from 16-bit buffer to be compatible with Zephyr standard.
Depends on [flash shall support changes](https://github.com/alifsemi/zephyr_alif/pull/88)

Samples: OSPI-Flash: 8-bit buffer support

---

west.yml

Update manifest to BLE address generation fix.
Depends on https://github.com/alifsemi/zephyr_alif/pull/107

manifest: update zephyr revision

---

west.yml

Update manifest for zephyr alif i2c update.
Depends on alifsemi/zephyr_alif#113.

manifest: zephyr_alif: revision update for I2C

---

west.yml

Update zephyr manifest revision to FPGA common dtsi fix.
Depends on alifsemi/zephyr_alif#117.

manifest: update to FPGA dtsi file fix.

---

samples/drivers/spi_flash/src/main.c

Fixed buffer count for xip read validation.

samples: drivers: ospi-flash: XiP Read verification

---

samples/modules/tflite-micro/alif_kws/boards/alif_b1_dk_rtss_he.overlay
samples/modules/tflite-micro/alif_kws/boards/alif_e1c_dk_rtss_he.overlay
samples/modules/tflite-micro/tflm_ethosu/boards/alif_b1_dk_rtss_he.overlay
samples/modules/tflite-micro/tflm_ethosu/boards/alif_e1c_dk_rtss_he.overlay

Updated sample overlays to use maximum OSPI clock speed on E1C and B1

samples: tflite-micro: Use maximum OSPI bus clock speed

---

samples/bluetooth/le_periph_blinky/boards/alif_b1_fpga_rtss_he_ble.overlay
samples/bluetooth/le_periph_blinky/src/main.c

Add support for BLE Rom version 1.2 to blinky application.
LEDs and Buttons not available for FPGA. However, a temporal overlay is added to ensure successful build.

samples: bluetooth: le_periph_blinky: Add support for BLE Rom v1.2

---

west.yml

Update zephyr manifest revision to spi rx_delay fix.
Depends on alifsemi/zephyr_Alif#118.

manifest: update to spi rx_delay fix

---

west.yml

Async UART fixes.
Relates to https://github.com/alifsemi/zephyr_alif/pull/125

manifest: zephyr update for async uart

---

samples/bluetooth/le_periph_plxp/src/main.c

- Add support for BLE ROM v1.2 to Pulse Oximeter sample application
- Rename boolean variable to lower case for consistency
- Add advertising address logs to identify units when running multiple devices

 samples: bluetooth: le_periph_plxp: BLE ROM v1.2 support

---

samples/drivers/display/boards/alif_e1c_dk_rtss_he.overlay

Enabling non secure node in overlay for e1c platform since by default it is disabled in dts.
Depends on alifsemi/zephyr_alif#138.

samples: display: enable non secure node in overlay

---

samples/drivers/ipm/ipm_arm_mhuv2/rtss_he/src/for_apss_mhu0.c
samples/drivers/ipm/ipm_arm_mhuv2/rtss_he/src/for_apss_mhu1.c
samples/drivers/ipm/ipm_arm_mhuv2/rtss_he/src/for_rtss_hp_mhu0.c
samples/drivers/ipm/ipm_arm_mhuv2/rtss_he/src/for_rtss_hp_mhu1.c
samples/drivers/ipm/ipm_arm_mhuv2/rtss_hp/src/for_apss_mhu0.c
samples/drivers/ipm/ipm_arm_mhuv2/rtss_hp/src/for_apss_mhu1.c
samples/drivers/ipm/ipm_arm_mhuv2/rtss_hp/src/for_rtss_he_mhu0.c
samples/drivers/ipm/ipm_arm_mhuv2/rtss_hp/src/for_rtss_he_mhu1.c

1. Updated callback parameters as per zephyr standard
2. user_data is any private data provided by app during initialization. It should be unmodified. So use last parameter to handle actual data.
This PR is dependent on PR: https://github.com/alifsemi/zephyr_alif/pull/120

samples: drivers: ipm: mhuv2: update callback params

---

drivers/i2s/i2s_sync/i2s_sync.c
samples/bluetooth/le_audio/broadcast_source/src/audio_datapath.c
samples/bluetooth/le_audio/broadcast_source/src/mic_source.c
samples/bluetooth/le_audio/unicast_sink/bidir.conf
samples/bluetooth/le_audio/unicast_sink/src/audio_datapath.c
samples/bluetooth/le_audio/unicast_source/bidir.conf
samples/bluetooth/le_audio/unicast_source/src/audio_datapath.c
samples/bluetooth/le_audio/unicast_source/src/unicast_source.c
subsys/bluetooth/le_audio/Kconfig
subsys/bluetooth/le_audio/audio_decoder.c
subsys/bluetooth/le_audio/audio_encoder.c
subsys/bluetooth/le_audio/audio_i2s_common.c
subsys/bluetooth/le_audio/audio_sink_i2s.c
subsys/bluetooth/le_audio/audio_source_i2s.c
subsys/bluetooth/le_audio/iso_datapath_ctoh.c
subsys/bluetooth/le_audio/iso_datapath_htoc.c

`__ramfunc` macro causes linking issue so make it optional to be able enabled if needed.

samples: bluetooth: le_audio: unidir: make __ramfunc optional

---

samples/bluetooth/le_periph_cgms/src/main.c
samples/bluetooth/le_periph_glps/src/main.c
samples/bluetooth/le_periph_prxp/src/main.c
west.yml

Since BLE ROM v1.2 the deprecated APIs are not available anymore.
Depends on alifsemi/zephyr_alif#183.

samples: ble: drops deprecated APIs

---

west.yml

zephyr updated to add spi mode selection from dts.
Depends on [Zephyr SPI Mode Selection PR#177](https://github.com/alifsemi/zephyr_alif/pull/177)

manifest: update zephyr to add spi mode selection fix.

---

west.yml

Update zephyr revision to include ns16550 uart reset support.
Depends on: https://github.com/alifsemi/zephyr_alif/pull/186

manifest: update zephyr revision to include uart reset support

---

samples/bluetooth/le_audio/broadcast_sink_sd/CMakeLists.txt
samples/bluetooth/le_audio/broadcast_sink_sd/Kconfig
samples/bluetooth/le_audio/broadcast_sink_sd/README.rst
samples/bluetooth/le_audio/broadcast_sink_sd/boards/alif_b1_dk_rtss_he.overlay
samples/bluetooth/le_audio/broadcast_sink_sd/overlay-dbg.conf
samples/bluetooth/le_audio/broadcast_sink_sd/prj.conf
samples/bluetooth/le_audio/broadcast_sink_sd/src/audio_datapath.c
samples/bluetooth/le_audio/broadcast_sink_sd/src/audio_datapath.h
samples/bluetooth/le_audio/broadcast_sink_sd/src/broadcast_sink.c
samples/bluetooth/le_audio/broadcast_sink_sd/src/broadcast_sink.h
samples/bluetooth/le_audio/broadcast_sink_sd/src/main.c

1. Added Scan Delegator role
2. BA can connect to device and do next actions:
- Start/stop scanning for the broadcast sources
- Add source
- Remove source
3. Modify source now is added but only for pa_sync = 0. Currently the app is tested with native
BLE Audio Broadcast Assistant on Samsung Galaxy S24 Ultra, and modify source request start
when "Leave" button pressed on connected broadcast source. The behavior of native BA on Samsung
cannot be fully debugged, so right now modify operation does the same as remove operation.
Testing procedure:
1. Start scanning BLE devices on the phone.
2. Pair and bond with sink device.
3. Start scanning for the sources.
4. Connect to source -> audio works.
5. Disconnect from source -> audio stops.
6. Repeat 4 and 5 for a few times.
Limitations:
1. Was …

 samples: bluetooth: le_audio: broadcast_sink_sd: Implement broadcast sink with scan delegator

---

samples/drivers/display/boards/alif_b1_dk_rtss_he.overlay
samples/drivers/display/boards/serial_display_1lane.overlay
west.yml

Enabled Non Secure node in overlays for single lane display and parallel display.

samples: drivers: display: Enable Non Secure node

---

west.yml

Update zephyr revision to add D/AVE2D into devicetree
Depends on alifsemi/zephyr_alif#193

manifest: update zephyr to add dave2d into devicetree

---

samples/drivers/video/boards/alif_b1_dk_rtss_he.overlay
samples/drivers/video/src/main.c

- Enabled NS node in sample overlay.
- Fixed pitch size calculation for Bayer10 format.
- Increased the NS region size from 384KB to 640KB.
- Depends on https://github.com/alifsemi/zephyr_alif/pull/200

samples: drivers: video: Enable NS node
