alifsemi/sdk-alif

CODEOWNERS
Added respective owners for the module/drivers.
=> CODEOWNERS: Updated Codeowners.

samples/bluetooth/le_periph_blps/src/main.c
Changes to BLPS semaphores names for easier reading.
=> samples: bluetooth: BLPS minor name changes

west.yml
=> west.yml: Update zas-v1.2

west.yml
=> west.yml: Update revision

samples/drivers/video/boards/parallel_camera_mt9m114.overlay, samples/drivers/video/boards/serial_camera_arx3a0.overlay
Updated the license information for the camera sensor overlay files.
=> samples: drivers: video: Update license information

samples/bluetooth/le_periph_cgms/prj.conf, samples/bluetooth/le_periph_cgms/src/main.c
Support to store bonding data in non-volatile storage partition.
=> samples: bluetooth: le_periph_cgms: Store bond data in NVS

west.yml
Updates vendor-prefixes.txt file.
=> manifest: Update zephyr_alif

doc/user_guide/source/building_application_binaries.rst
=> Updated section on Building Application Binaries

west.yml
Fixes the documentation to exec from MRAM.
=> manifest: Updates Zephyr

west.yml
Related to HAL Alif [PR12](https://github.com/alifsemi/hal_alif/pull/12)
=> mainifest: Zephyr Alif updated

west.yml
Update zephyr revision in manifest.
Depends on https://github.com/alifsemi/zephyr_alif/pull/57
=> manifest: Update zephyr revision

samples/bluetooth/le_audio/unicast_sink/src/main.c, samples/bluetooth/le_audio/unicast_sink/src/unicast_sink.c, samples/bluetooth/le_audio/unicast_sink/src/unicast_sink.h, samples/bluetooth/le_audio/unicast_source/src/audio_datapath.c, samples/bluetooth/le_audio/unicast_source/src/main.c, samples/bluetooth/le_audio/unicast_source/src/main.h, samples/bluetooth/le_audio/unicast_source/src/storage.c, samples/bluetooth/le_audio/unicast_source/src/unicast_source.c
Add support for bonding and fix control delay issue with Androin phone. 
Code cleanups and small fine tunings to stream controls.
Fix ROM 1.2 related issues.
=> samples: Add bonding support to unicast LE audio samples

west.yml
External flash memory regions.
=> manifest: Zephyr manifest update

samples/bluetooth/smp_svr/README.rst
Update flashing instructions to use Alif SETools.
=> samples: bluetooth: smp_svr: Update documentation

Jenkinsfile, test_samples.groovy
This PR enables compiling of various sample applications
=> Added JenkinsFile & .groovy file to run some basic CI checks

test_samples.groovy
git clean added to have clean git repository before tests
=> Minor fixes for Groovy file

samples/drivers/ipm/ipm_arm_mhuv2/rtss_he/README.rst, samples/drivers/ipm/ipm_arm_mhuv2/rtss_he/src/for_apss_mhu0.c, samples/drivers/ipm/ipm_arm_mhuv2/rtss_he/src/for_apss_mhu1.c, samples/drivers/ipm/ipm_arm_mhuv2/rtss_he/src/for_rtss_hp_mhu0.c, samples/drivers/ipm/ipm_arm_mhuv2/rtss_he/src/for_rtss_hp_mhu1.c, samples/drivers/ipm/ipm_arm_mhuv2/rtss_he/src/se_service_test.c, samples/drivers/ipm/ipm_arm_mhuv2/rtss_hp/README.rst, samples/drivers/ipm/ipm_arm_mhuv2/rtss_hp/src/for_apss_mhu0.c, samples/drivers/ipm/ipm_arm_mhuv2/rtss_hp/src/for_apss_mhu1.c, samples/drivers/ipm/ipm_arm_mhuv2/rtss_hp/src/for_rtss_he_mhu0.c, samples/drivers/ipm/ipm_arm_mhuv2/rtss_hp/src/for_rtss_he_mhu1.c, samples/drivers/ipm/ipm_arm_mhuv2/rtss_hp/src/se_service_test.c
Updated MHU driver api calls in MHU v2 apps.
Depends on alifsemi/zephyr_alif#53.
=> samples: drivers: ipm: ipm_arm_mhuv2: update MHU v2 apps

README.md
Updated Readme to the latest release links.
=> Updated Readme links to point to latest 1.2 ZAS release.

samples/bluetooth/smp_svr/CMakeLists.txt, samples/bluetooth/smp_svr/src/main.c
Add support for battery service and BLE v1.2 to smp_svr sample application.
=> samples: bluetooth: smp_svr: smp support for battery and ROM v1.2

samples/drivers/video/README.rst, samples/drivers/video/boards/serial_camera_hm0360.overlay, west.yml
Add HM0360 CMOS sensor overlay to video testcase
=> samples: overlays: HM0360 CMOS sensor overlay

samples/drivers/dac/CMakeLists.txt, samples/drivers/dac/README.rst, samples/drivers/dac/boards/alif_b1_dk_rtss_he.overlay, samples/drivers/dac/boards/alif_e1c_dk_rtss_he.overlay, samples/drivers/dac/boards/alif_e3_dk_rtss_he.overlay, samples/drivers/dac/boards/alif_e3_dk_rtss_hp.overlay, samples/drivers/dac/boards/alif_e7_dk_rtss_he.overlay, samples/drivers/dac/boards/alif_e7_dk_rtss_hp.overlay, samples/drivers/dac/prj.conf, samples/drivers/dac/sample.yaml, samples/drivers/dac/src/main.c
Added test application and overlay file for
E1C/B1/E7/E3 boards.
=> samples: drivers: DAC: Add Test application and overlay

west.yml
Update manifest for zephyr alif SD updates.
=> manifest: zephyr_alif: revision update for SD

applications/testapp/readme.rst
Add information how to start openthread with manual start enabled
=> applications: test application README update

README.md, doc/release_notes/source/conf.py, doc/user_guide/source/building_application_binaries.rst, doc/user_guide/source/conf.py
- Revise README for Alif SDK with improved clarity and details
- Update copyright year in conf.py for User Guide and Release Notes
=> Update README and copyright year in documentation

samples/bluetooth/common/batt_svc.c, samples/bluetooth/le_periph_prxp/CMakeLists.txt, samples/bluetooth/le_periph_prxp/inc/prxp_app.h, samples/bluetooth/le_periph_prxp/src/main.c, samples/bluetooth/le_periph_prxp/src/prxp_rom_1_0.c, samples/bluetooth/le_periph_prxp/src/prxp_rom_1_2.c
Refactor and add ROM v1.2 support to proximity sample application.
Includes a specific file for each ROM version.
=> samples: bluetooth: le_periph_prxp: Proximity app refactor.

west.yml
Updated zephyr_alif rev in west.yml.
Depends on alifsemi/zephyr_alif#114.
=> manifest: update zephyr_alif rev

west.yml
Update zephyr manifest revision to fs_sample fix.
=> manifest: update to fs_sample fix

west.yml
Depends on alifsemi/zephyr_alif#102.
=> Zephyr_alif updated

samples/bluetooth/le_periph/src/main.c
Add support for BLE Rom version 1.2 to le_periph app.
=> samples: bluetooth: le_periph: Add support for BLE Rom v1.2

samples/bluetooth/le_periph_blps/CMakeLists.txt, samples/bluetooth/le_periph_blps/src/main.c
Add support for BLE ROM v1.2 and for independent battery service to Blood Presuure sample applicaion.
=> samples: bluetooth: le_periph_blps: BLE ROMv.2 and battery svc update.

samples/drivers/ipm/ipm_arm_mhuv2/rtss_he/README.rst, samples/drivers/ipm/ipm_arm_mhuv2/rtss_he/src/for_apss_mhu0.c, samples/drivers/ipm/ipm_arm_mhuv2/rtss_he/src/for_apss_mhu1.c, samples/drivers/ipm/ipm_arm_mhuv2/rtss_he/src/for_rtss_hp_mhu0.c, samples/drivers/ipm/ipm_arm_mhuv2/rtss_he/src/for_rtss_hp_mhu1.c, samples/drivers/ipm/ipm_arm_mhuv2/rtss_hp/README.rst, samples/drivers/ipm/ipm_arm_mhuv2/rtss_hp/src/for_apss_mhu0.c, samples/drivers/ipm/ipm_arm_mhuv2/rtss_hp/src/for_apss_mhu1.c, samples/drivers/ipm/ipm_arm_mhuv2/rtss_hp/src/for_rtss_he_mhu0.c, samples/drivers/ipm/ipm_arm_mhuv2/rtss_hp/src/for_rtss_he_mhu1.c
Print the value of Tx msg being sent
=> samples: drivers: ipm: mhuv2: add tx msg prints

samples/bluetooth/le_periph_cpps/src/main.c
Add suport for BLE ROM v1.2 to Cycling Power Service sample application.
=> samples: bluetooth: le_periph_cpps: Add support for BLE ROM v1.2

subsys/powermgr/shell/src/power_mgr_shell.c
Add dynamic pinmux configuration to enable external HCI connection
=> powermgr: Add support for pinmuxing of External HCI

west.yml
West.yml updated to get hal_alif changes in.
See: https://github.com/alifsemi/zephyr_alif/pull/137
=> Added configs for sleep clock and active clock drifts

west.yml
=> manifest: Fix NVDS length calculation

samples/bluetooth/le_periph_glps/CMakeLists.txt, samples/bluetooth/le_periph_glps/src/main.c, samples/bluetooth/le_periph_glps/src/rtc_emulator.c
Add support for BLE ROM v1.2 and independent Battery Service to Glucose Profile sample application.
=> samples: bluetooth: le_periph_glps: Add support for BLE ROMv1.2

samples/bluetooth/le_periph_hr/CMakeLists.txt, samples/bluetooth/le_periph_hr/src/main.c
- Add independent Battery service to Hear Rate sample application.
=>  samples: bluetooth: le_periph_hr: sample independent Battery Service

samples/drivers/i2c_dw/boards/alif_e3_dk_rtss_he.overlay, samples/drivers/i2c_dw/boards/alif_e3_dk_rtss_hp.overlay
Added E3 support for I2C_dw Driver.
=> samples: drivers: i2c_dw: Add E3 support

Jenkinsfile, test_samples.groovy
This far a build error has gotten unnoticed.
=> automation: fail on build failure

samples/bluetooth/le_periph_pm/src/main.c
Add support for BLE ROM v1.2 to Power Management sample application.
=> samples: bluetooth: le_periph_pm: Add support for BLE ROM v1.2

west.yml
Update zephyr revision to patching fix.
Depends on zephyr PR 151: https://github.com/alifsemi/zephyr_alif/pull/151
=> manifest: update zephyr revision to patching_fix

west.yml
Take a pwm driver fix.
https://github.com/alifsemi/zephyr_alif/pull/155
=> manifest: Update Zephyr manifest

samples/drivers/spi_dw/README.rst, samples/drivers/spi_dw/boards/alif_e1c_dk_rtss_he.overlay
modified console log to lpuart from uart2.
=> samples: drivers: spi_dw: e1c overlay

west.yml
hal_alif license update.
Depends on alifsemi/zephyr_alif#154.
=> manifest: updates zephyr_alif

west.yml
Balletto startup code optimization to power peripherals base on dts configuration.
Zephyr PR: https://github.com/alifsemi/zephyr_alif/pull/160
=> manifest: update zephyr (Balletto power based on dts)

samples/bluetooth/common/address_verification.c, samples/bluetooth/common/address_verification.h, samples/bluetooth/le_periph_blinky/CMakeLists.txt, samples/bluetooth/le_periph_blinky/prj.conf, samples/bluetooth/le_periph_blinky/src/main.c
Add BLE address verification to blinky application.
=> samples: bluetooth: le_periph_blinky: BLE address verification

west.yml
Added FPU support for B1 with hard ABI
=> boards: arm: alif_b1_dk: Add support for FPU

automation/Jenkinsfile_Pr, automation/check_uart_output.py
This is for Pr testing for test-app. It will build flash and make smoke test
=> Pr check for test-app

samples/bluetooth/le_periph_cgms/src/main.c, samples/bluetooth/le_periph_glps/src/main.c, samples/bluetooth/le_periph_prxp/src/main.c, west.yml
=> Revert "samples: ble: drops deprecated APIs"

west.yml
Take HCI / AHI  uart DMA support.
depends on https://github.com/alifsemi/zephyr_alif/pull/187
=> manifest: Update zephyr

drivers/i2s/i2s_sync/i2s_sync.c, samples/bluetooth/le_audio/broadcast_mode_switch/CMakeLists.txt, samples/bluetooth/le_audio/broadcast_mode_switch/Kconfig, samples/bluetooth/le_audio/broadcast_mode_switch/README.rst, samples/bluetooth/le_audio/broadcast_mode_switch/boards/alif_b1_dk_rtss_he.overlay, samples/bluetooth/le_audio/broadcast_mode_switch/overlay-dbg.conf, samples/bluetooth/le_audio/broadcast_mode_switch/prj.conf, samples/bluetooth/le_audio/broadcast_mode_switch/src/audio_datapath.c, samples/bluetooth/le_audio/broadcast_mode_switch/src/audio_datapath.h, samples/bluetooth/le_audio/broadcast_mode_switch/src/broadcast_sink.c, samples/bluetooth/le_audio/broadcast_mode_switch/src/broadcast_sink.h, samples/bluetooth/le_audio/broadcast_mode_switch/src/broadcast_source.c, samples/bluetooth/le_audio/broadcast_mode_switch/src/broadcast_source.h, samples/bluetooth/le_audio/broadcast_mode_switch/src/main.c, samples/bluetooth/le_audio/broadcast_mode_switch/src/mode_switch_service.c, samples/bluetooth/le_audio/broadcast_mode_switch/src/mode_switch_service.h
Added fix to properly stop DMA on I2S stop.
Implemented broadcast sink/source switch application.
1. Created custom service which handles role switches.
2. Available 3 modes: idle, sink, source.
3. User can write to service the values of the mode to switch in another service.
4. Sink and source are implemented from basic examples with proper stop.
=>  samples: bluetooth: broadcast_mode_switch: Implement sink source switch application

include/alif/bluetooth/bt_adv_data.h, include/alif/bluetooth/bt_scan_rsp.h, include/alif/bluetooth/bt_srv_hello.h, subsys/bluetooth/CMakeLists.txt, subsys/bluetooth/host/CMakeLists.txt, subsys/bluetooth/host/Kconfig, subsys/bluetooth/host/bt_adv_data.c, subsys/bluetooth/host/bt_scan_rsp.c, subsys/bluetooth/host/bt_srv_hello.c, subsys/bluetooth/shell/CMakeLists.txt, subsys/bluetooth/shell/bt.c, tests/bluetooth/shell_peripheral/src/main.c
Only possible to set device name for now.
=> bluetooth: setting advertising data

automation/Jenkinsfile_Pr
=> This will build all sdk-alif/samples/Bluetooth samples
